{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/okta-mobile-swift/development/documentation\/authfoundation\/oktaapierror\/errordescription-336gx"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AuthFoundation\/okta-mobile-swift/development/documentation\/AuthFoundation\/OktaAPIError\/errorDescription-336gx","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"errorDescription","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:14AuthFoundation12OktaAPIErrorV16errorDescriptionSSSgvp","modules":[{"name":"AuthFoundation"}]},"hierarchy":{"paths":[["doc:\/\/AuthFoundation\/okta-mobile-swift/development/documentation\/AuthFoundation","doc:\/\/AuthFoundation\/okta-mobile-swift/development/documentation\/AuthFoundation\/OktaAPIError"]]},"references":{"doc://AuthFoundation/okta-mobile-swift/development/documentation/AuthFoundation":{"role":"collection","title":"AuthFoundation","abstract":[{"type":"text","text":"Library that provides foundational features used by Oktaâ€™s authentication libraries, as well as APIs used to work with tokens and user credentials."}],"identifier":"doc:\/\/AuthFoundation\/okta-mobile-swift/development/documentation\/AuthFoundation","kind":"symbol","type":"topic","url":"\/okta-mobile-swift/development/documentation\/authfoundation"},"doc://AuthFoundation/okta-mobile-swift/development/documentation/AuthFoundation/OktaAPIError/errorDescription-336gx":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/okta-mobile-swift/development/documentation\/AuthFoundation\/OktaAPIError\/errorDescription-336gx","kind":"symbol","type":"topic","url":"\/okta-mobile-swift/development/documentation\/authfoundation\/oktaapierror\/errordescription-336gx"},"doc://AuthFoundation/okta-mobile-swift/development/documentation/AuthFoundation/OktaAPIError":{"role":"symbol","title":"OktaAPIError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OktaAPIError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/okta-mobile-swift/development/documentation\/AuthFoundation\/OktaAPIError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OktaAPIError"}],"url":"\/okta-mobile-swift/development/documentation\/authfoundation\/oktaapierror"}}}