{
  "abstract" : [
    {
      "text" : "Thrown when a credential no longer has a weak reference to the coordinator that was used to create it.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.okta.mobile.oktaoauth2\/documentation\/AuthFoundation",
        "doc:\/\/com.okta.mobile.oktaoauth2\/documentation\/AuthFoundation\/CredentialError"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.okta.mobile.oktaoauth2\/documentation\/AuthFoundation\/CredentialError\/missingCoordinator"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "s:14AuthFoundation15CredentialErrorO18missingCoordinatoryA2CmF",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "case"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "missingCoordinator"
      }
    ],
    "modules" : [
      {
        "name" : "AuthFoundation"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Case",
    "symbolKind" : "case",
    "title" : "CredentialError.missingCoordinator"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "macOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "case"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "missingCoordinator"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 2,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/authfoundation\/credentialerror\/missingcoordinator"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.okta.mobile.oktaoauth2/documentation/AuthFoundation": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.okta.mobile.oktaoauth2\/documentation\/AuthFoundation",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "AuthFoundation",
  "type" : "topic",
  "url" : "\/documentation\/authfoundation"
},
"doc://com.okta.mobile.oktaoauth2/documentation/AuthFoundation/CredentialError": {
  "abstract" : [
    {
      "text" : "Errors that may occur in the process of managing credentials.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "enum"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "CredentialError"
    }
  ],
  "identifier" : "doc:\/\/com.okta.mobile.oktaoauth2\/documentation\/AuthFoundation\/CredentialError",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "CredentialError"
    }
  ],
  "role" : "symbol",
  "title" : "CredentialError",
  "type" : "topic",
  "url" : "\/documentation\/authfoundation\/credentialerror"
},
"doc://com.okta.mobile.oktaoauth2/documentation/AuthFoundation/CredentialError/missingCoordinator": {
  "abstract" : [
    {
      "text" : "Thrown when a credential no longer has a weak reference to the coordinator that was used to create it.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "case"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "missingCoordinator"
    }
  ],
  "identifier" : "doc:\/\/com.okta.mobile.oktaoauth2\/documentation\/AuthFoundation\/CredentialError\/missingCoordinator",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "CredentialError.missingCoordinator",
  "type" : "topic",
  "url" : "\/documentation\/authfoundation\/credentialerror\/missingcoordinator"
}
}
}