{"seeAlsoSections":[{"title":"Error Types","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/APIClientError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/TokenError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/JWTError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/KeychainError"],"generated":true}],"schemaVersion":{"major":0,"minor":2,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"title":"AuthenticationError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:14AuthFoundation19AuthenticationErrorO","modules":[{"name":"AuthFoundation"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}]},"abstract":[{"type":"text","text":"Errors that may be generated during the process of authenticating with a variety of authentication flows."}],"sections":[],"identifier":{"url":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/AuthFoundation\/SQ","doc:\/\/AuthFoundation\/s5ErrorP","doc:\/\/AuthFoundation\/SH","doc:\/\/AuthFoundation\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/AuthFoundation\/documentation\/AuthFoundation"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError\/flowNotReady"]},{"title":"Default Implementations","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError\/Equatable-Implementations","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError\/Error-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/authfoundation\/authenticationerror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"languages":["swift"],"platforms":["macOS"]}]}],"references":{"doc://AuthFoundation/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/AuthFoundation\/s5ErrorP"},"doc://AuthFoundation/documentation/AuthFoundation/AuthenticationError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/authfoundation\/authenticationerror\/error-implementations"},"doc://AuthFoundation/documentation/AuthFoundation/AuthenticationError/flowNotReady":{"role":"symbol","title":"AuthenticationError.flowNotReady","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"flowNotReady"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError\/flowNotReady","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/authenticationerror\/flownotready"},"doc://AuthFoundation/documentation/AuthFoundation/AuthenticationError":{"role":"symbol","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"Errors that may be generated during the process of authenticating with a variety of authentication flows."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"url":"\/documentation\/authfoundation\/authenticationerror"},"doc://AuthFoundation/documentation/AuthFoundation/KeychainError":{"role":"symbol","title":"KeychainError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/KeychainError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainError"}],"url":"\/documentation\/authfoundation\/keychainerror"},"doc://AuthFoundation/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AuthFoundation\/s8SendableP"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error":{"role":"symbol","title":"OAuth2Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2Error"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2Error"}],"url":"\/documentation\/authfoundation\/oauth2error"},"doc://AuthFoundation/documentation/AuthFoundation/JWTError":{"role":"symbol","title":"JWTError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWTError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/JWTError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JWTError"}],"url":"\/documentation\/authfoundation\/jwterror"},"doc://AuthFoundation/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/AuthFoundation\/SQ"},"doc://AuthFoundation/documentation/AuthFoundation/CredentialError":{"role":"symbol","title":"CredentialError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialError"}],"abstract":[{"type":"text","text":"Errors that may occur in the process of managing credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CredentialError"}],"url":"\/documentation\/authfoundation\/credentialerror"},"doc://AuthFoundation/documentation/AuthFoundation/APIClientError":{"role":"symbol","title":"APIClientError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIClientError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/APIClientError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIClientError"}],"url":"\/documentation\/authfoundation\/apiclienterror"},"doc://AuthFoundation/documentation/AuthFoundation/AuthenticationError/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/authfoundation\/authenticationerror\/equatable-implementations"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2ServerError":{"role":"symbol","title":"OAuth2ServerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2ServerError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2ServerError"}],"url":"\/documentation\/authfoundation\/oauth2servererror"},"doc://AuthFoundation/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/AuthFoundation\/SH"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError":{"role":"symbol","title":"OktaAPIError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OktaAPIError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OktaAPIError"}],"url":"\/documentation\/authfoundation\/oktaapierror"},"doc://AuthFoundation/documentation/AuthFoundation":{"role":"collection","title":"AuthFoundation","abstract":[{"type":"text","text":"Library that provides foundational features used by Oktaâ€™s authentication libraries, as well as APIs used to work with tokens and user credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation"},"doc://AuthFoundation/documentation/AuthFoundation/TokenError":{"role":"symbol","title":"TokenError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokenError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/TokenError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TokenError"}],"url":"\/documentation\/authfoundation\/tokenerror"}}}