{"seeAlsoSections":[{"title":"Error Types","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/APIClientError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/TokenError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/JWTError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/KeychainError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError"],"generated":true}],"schemaVersion":{"major":0,"minor":2,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OktaAPIError"}],"title":"OktaAPIError","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:14AuthFoundation12OktaAPIErrorV","modules":[{"name":"AuthFoundation"}],"navigatorTitle":[{"kind":"identifier","text":"OktaAPIError"}]},"abstract":[{"type":"text","text":"No overview available."}],"sections":[],"identifier":{"url":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/AuthFoundation\/10Foundation14LocalizedErrorP","doc:\/\/AuthFoundation\/Se","doc:\/\/AuthFoundation\/s5ErrorP","doc:\/\/AuthFoundation\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/AuthFoundation\/documentation\/AuthFoundation"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/causes","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/code","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/errorDescription-336gx","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/id","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/link","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/summary"]},{"title":"Default Implementations","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/Error-Implementations","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/LocalizedError-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/authfoundation\/oktaapierror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OktaAPIError"}],"languages":["swift"],"platforms":["macOS"]}]}],"references":{"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/init(from:)"},"doc://AuthFoundation/documentation/AuthFoundation/AuthenticationError":{"role":"symbol","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"Errors that may be generated during the process of authenticating with a variety of authentication flows."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"url":"\/documentation\/authfoundation\/authenticationerror"},"doc://AuthFoundation/documentation/AuthFoundation/APIClientError":{"role":"symbol","title":"APIClientError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIClientError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/APIClientError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIClientError"}],"url":"\/documentation\/authfoundation\/apiclienterror"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError/link":{"role":"symbol","title":"link","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/link","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/link"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error":{"role":"symbol","title":"OAuth2Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2Error"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2Error"}],"url":"\/documentation\/authfoundation\/oauth2error"},"doc://AuthFoundation/documentation/AuthFoundation":{"role":"collection","title":"AuthFoundation","abstract":[{"type":"text","text":"Library that provides foundational features used by Oktaâ€™s authentication libraries, as well as APIs used to work with tokens and user credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError/id":{"role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/id","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/id"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError/errorDescription-336gx":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/errorDescription-336gx","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/errordescription-336gx"},"doc://AuthFoundation/documentation/AuthFoundation/JWTError":{"role":"symbol","title":"JWTError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWTError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/JWTError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JWTError"}],"url":"\/documentation\/authfoundation\/jwterror"},"doc://AuthFoundation/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AuthFoundation\/s8SendableP"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError/causes":{"role":"symbol","title":"causes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"causes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/causes","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/causes"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/localizederror-implementations"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/error-implementations"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2ServerError":{"role":"symbol","title":"OAuth2ServerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2ServerError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2ServerError"}],"url":"\/documentation\/authfoundation\/oauth2servererror"},"doc://AuthFoundation/documentation/AuthFoundation/TokenError":{"role":"symbol","title":"TokenError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokenError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/TokenError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TokenError"}],"url":"\/documentation\/authfoundation\/tokenerror"},"doc://AuthFoundation/documentation/AuthFoundation/KeychainError":{"role":"symbol","title":"KeychainError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/KeychainError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainError"}],"url":"\/documentation\/authfoundation\/keychainerror"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError/code":{"role":"symbol","title":"code","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/code","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/code"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError/summary":{"role":"symbol","title":"summary","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"summary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError\/summary","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/summary"},"doc://AuthFoundation/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/AuthFoundation\/10Foundation14LocalizedErrorP"},"doc://AuthFoundation/documentation/AuthFoundation/CredentialError":{"role":"symbol","title":"CredentialError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialError"}],"abstract":[{"type":"text","text":"Errors that may occur in the process of managing credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CredentialError"}],"url":"\/documentation\/authfoundation\/credentialerror"},"doc://AuthFoundation/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/AuthFoundation\/s5ErrorP"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError":{"role":"symbol","title":"OktaAPIError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OktaAPIError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OktaAPIError"}],"url":"\/documentation\/authfoundation\/oktaapierror"},"doc://AuthFoundation/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/AuthFoundation\/Se"}}}