{"seeAlsoSections":[{"title":"Error Types","identifiers":["doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/APIClientError","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OAuth2Error","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OAuth2ServerError","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/CredentialError","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/TokenError","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/JWTError","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/KeychainError","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/AuthenticationError"],"generated":true}],"schemaVersion":{"major":0,"minor":2,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OktaAPIError"}],"title":"OktaAPIError","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:14AuthFoundation12OktaAPIErrorV","modules":[{"name":"AuthFoundation"}],"navigatorTitle":[{"kind":"identifier","text":"OktaAPIError"}]},"abstract":[{"type":"text","text":"Describes errors that may be reported from an Okta API endpoint."}],"sections":[],"identifier":{"url":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.okta.mobile.authfoundation\/10Foundation14LocalizedErrorP","doc:\/\/com.okta.mobile.authfoundation\/Se","doc:\/\/com.okta.mobile.authfoundation\/s5ErrorP","doc:\/\/com.okta.mobile.authfoundation\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/init(from:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/causes","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/code","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/errorDescription-336gx","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/id","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/link","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/summary"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/Error-Implementations","doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/LocalizedError-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/authfoundation\/oktaapierror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OktaAPIError"}],"languages":["swift"],"platforms":["macOS"]}]}],"references":{"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OAuth2ServerError":{"role":"symbol","title":"OAuth2ServerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2ServerError"}],"abstract":[{"type":"text","text":"Describes errors reported from an OAuth2 server."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OAuth2ServerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2ServerError"}],"url":"\/documentation\/authfoundation\/oauth2servererror"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/JWTError":{"role":"symbol","title":"JWTError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWTError"}],"abstract":[{"type":"text","text":"Describes errors that may occur with parsing or validating JWT tokens."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/JWTError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JWTError"}],"url":"\/documentation\/authfoundation\/jwterror"},"doc://com.okta.mobile.authfoundation/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.okta.mobile.authfoundation\/10Foundation14LocalizedErrorP"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/error-implementations"},"doc://com.okta.mobile.authfoundation/Se":{"type":"unresolvable","title":"Swift.Decodable","identifier":"doc:\/\/com.okta.mobile.authfoundation\/Se"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError":{"role":"symbol","title":"OktaAPIError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OktaAPIError"}],"abstract":[{"type":"text","text":"Describes errors that may be reported from an Okta API endpoint."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OktaAPIError"}],"url":"\/documentation\/authfoundation\/oktaapierror"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OAuth2Error":{"role":"symbol","title":"OAuth2Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2Error"}],"abstract":[{"type":"text","text":"Errors that may occur when interacting with OAuth2 endpoints."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OAuth2Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2Error"}],"url":"\/documentation\/authfoundation\/oauth2error"},"doc://com.okta.mobile.authfoundation/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.okta.mobile.authfoundation\/s8SendableP"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError/errorDescription-336gx":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A localized message describing what error occurred."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/errorDescription-336gx","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/errordescription-336gx"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/TokenError":{"role":"symbol","title":"TokenError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokenError"}],"abstract":[{"type":"text","text":"Describes errors that may occur when working with tokens."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/TokenError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TokenError"}],"url":"\/documentation\/authfoundation\/tokenerror"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/AuthenticationError":{"role":"symbol","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"Errors that may be generated during the process of authenticating with a variety of authentication flows."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/AuthenticationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"url":"\/documentation\/authfoundation\/authenticationerror"},"doc://com.okta.mobile.authfoundation/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.okta.mobile.authfoundation\/s5ErrorP"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError/init(from:)":{"role":"symbol","title":"init(from:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Decoder","preciseIdentifier":"s:s7DecoderP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Creates a new instance by decoding from the given decoder."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/init(from:)","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/init(from:)"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/KeychainError":{"role":"symbol","title":"KeychainError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainError"}],"abstract":[{"type":"text","text":"Describes errors that may occur when interacting with the keychain."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/KeychainError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainError"}],"url":"\/documentation\/authfoundation\/keychainerror"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation":{"role":"collection","title":"AuthFoundation","abstract":[{"type":"text","text":"Library that provides foundational features used by Okta’s authentication libraries, as well as APIs used to work with tokens and user credentials."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/CredentialError":{"role":"symbol","title":"CredentialError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialError"}],"abstract":[{"type":"text","text":"Errors that may occur in the process of managing credentials."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/CredentialError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CredentialError"}],"url":"\/documentation\/authfoundation\/credentialerror"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError/summary":{"role":"symbol","title":"summary","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"summary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"A short description of what caused this error. Sometimes this contains dynamically-generated information about your specific error."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/summary","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/summary"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError/id":{"role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"A unique identifier for this error. This can be used by Okta Support to help with troubleshooting."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/id","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/id"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError/code":{"role":"symbol","title":"code","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"An Okta code for this type of error."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/code","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/code"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError/causes":{"role":"symbol","title":"causes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"causes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Further information about what caused this error."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/causes","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/causes"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/localizederror-implementations"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/OktaAPIError/link":{"role":"symbol","title":"link","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"link"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"An Okta code for this type of error"}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/OktaAPIError\/link","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oktaapierror\/link"},"doc://com.okta.mobile.authfoundation/documentation/AuthFoundation/APIClientError":{"role":"symbol","title":"APIClientError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIClientError"}],"abstract":[{"type":"text","text":"Errors that may occur at the API or network level."}],"identifier":"doc:\/\/com.okta.mobile.authfoundation\/documentation\/AuthFoundation\/APIClientError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIClientError"}],"url":"\/documentation\/authfoundation\/apiclienterror"}}}